language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get update
  - sudo apt-get install -y ocaml ocaml-doc opam  
      ocaml-native-compilers menhir
  - opam init -n
  - eval `opam config env`
  - opam install core -y
# command to run tests
script: make
